spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:\Users\krzys\Desktop\Academic Projects\Object and Component Technologies\Sikora_Ksiazek_Ciochon\MovieApp\uploads
app:
  storage:
    location: C:\Users\krzys\Desktop\Academic Projects\Object and Component Technologies\Sikora_Ksiazek_Ciochon\MovieApp\uploads